"""
dbt Cloud project bootstrap — Streamlit UI.
Run: streamlit run app.py
"""
import os
import shutil
import subprocess
import tempfile
from pathlib import Path

import streamlit as st

# Path to this repo (where .tf files live)
REPO_DIR = Path(__file__).resolve().parent
TF_FILES = ["main.tf", "tf_dbt.tf", "variables.tf"]
LOCK_FILE = ".terraform.lock.hcl"


def ensure_session_workspace():
    """Create a temp workspace for this session and copy Terraform files into it."""
    if "workspace_dir" not in st.session_state:
        st.session_state.workspace_dir = tempfile.mkdtemp(prefix="tf_dbt_")
        for name in TF_FILES:
            src = REPO_DIR / name
            if src.exists():
                shutil.copy2(src, Path(st.session_state.workspace_dir) / name)
        lock_src = REPO_DIR / LOCK_FILE
        if lock_src.exists():
            shutil.copy2(lock_src, Path(st.session_state.workspace_dir) / LOCK_FILE)
    return st.session_state.workspace_dir


def build_tfvars(
    dbt_cloud_account_id,
    project_id,
    project_name,
    project_description,
    project_type,
    connection_id,
    credential_id,
    dbt_cloud_host_url,
    dbt_version,
    staging_branch,
    schedule_cron,
    num_threads,
    deactivate_jobs_pr,
    deactivate_jobs_merge,
    deactivate_jobs_schedule,
):
    """Build terraform.tfvars content from form values."""
    lines = [
        "# Generated by Streamlit app",
        "",
        "dbt_cloud_account_id = " + str(int(dbt_cloud_account_id)),
        "",
    ]
    if project_id is not None and str(project_id).strip() != "":
        try:
            pid = int(project_id)
            lines.append("# Use existing project")
            lines.append("project_id = " + str(pid))
        except (TypeError, ValueError):
            pass
    else:
        lines.append("# Create new project")
        lines.append("project_id = null")
        if project_name:
            lines.append('project_name = "' + str(project_name).replace('"', '\\"') + '"')
        if project_description:
            lines.append('project_description = "' + str(project_description).replace('"', '\\"') + '"')
        if project_type is not None:
            lines.append("project_type = " + str(int(project_type)))
    lines.append("")
    lines.append("connection_id = " + str(int(connection_id)))
    lines.append("credential_id = " + str(int(credential_id)))
    lines.append("")
    if dbt_cloud_host_url:
        lines.append('dbt_cloud_host_url = "' + str(dbt_cloud_host_url).replace('"', '\\"') + '"')
        lines.append("")
    if dbt_version:
        lines.append('dbt_version = "' + str(dbt_version).replace('"', '\\"') + '"')
    if staging_branch:
        lines.append('staging_branch = "' + str(staging_branch).replace('"', '\\"') + '"')
    if schedule_cron:
        lines.append('schedule_cron = "' + str(schedule_cron).replace('"', '\\"') + '"')
    if num_threads is not None:
        lines.append("num_threads = " + str(int(num_threads)))
    if deactivate_jobs_pr or deactivate_jobs_merge or deactivate_jobs_schedule:
        lines.append("")
        lines.append("deactivate_jobs_pr = " + ("true" if deactivate_jobs_pr else "false"))
        lines.append("deactivate_jobs_merge = " + ("true" if deactivate_jobs_merge else "false"))
        lines.append("deactivate_jobs_schedule = " + ("true" if deactivate_jobs_schedule else "false"))
    return "\n".join(lines)


def run_terraform(workspace_dir, token, *args):
    """Run terraform in workspace_dir with DBT_CLOUD_TOKEN set. Returns (success, stdout, stderr)."""
    env = os.environ.copy()
    if token:
        env["DBT_CLOUD_TOKEN"] = token
    try:
        result = subprocess.run(
            ["terraform"] + list(args),
            cwd=workspace_dir,
            env=env,
            capture_output=True,
            text=True,
            timeout=300,
        )
        return result.returncode == 0, result.stdout, result.stderr
    except FileNotFoundError:
        return False, "", "Terraform CLI not found. Install Terraform and ensure it is on PATH."
    except subprocess.TimeoutExpired:
        return False, "", "Terraform command timed out."


def main():
    st.set_page_config(page_title="dbt Cloud bootstrap", layout="wide")
    st.title("dbt Cloud project bootstrap")
    st.caption("One-time setup: environments and jobs. State is session-only — close the browser and it’s gone.")

    # Token (session state so it persists during session)
    token_placeholder = st.empty()
    if "dbt_token" not in st.session_state:
        st.session_state.dbt_token = ""
    token = token_placeholder.text_input(
        "DBT_CLOUD_TOKEN",
        value=st.session_state.dbt_token,
        type="password",
        help="dbt Cloud API token (stored only in this session).",
    )
    if token != st.session_state.dbt_token:
        st.session_state.dbt_token = token

    st.divider()

    # Required
    st.subheader("Required")
    col1, col2, col3 = st.columns(3)
    with col1:
        dbt_cloud_account_id = st.number_input("dbt_cloud_account_id", min_value=1, value=51798, step=1)
    with col2:
        connection_id = st.number_input("connection_id", min_value=1, value=51284, step=1)
    with col3:
        credential_id = st.number_input("credential_id", min_value=1, value=487354, step=1)

    # Project: existing vs new
    st.subheader("Project")
    use_existing = st.radio("Project", ["Use existing project (by ID)", "Create new project"], horizontal=True)
    if use_existing == "Use existing project (by ID)":
        project_id = st.number_input("project_id", min_value=1, value=512261, step=1)
        project_name = None
        project_description = ""
        project_type = 0
    else:
        project_id = None
        project_name = st.text_input("project_name", value="My dbt Project", placeholder="Project name")
        project_description = st.text_input("project_description", value="", placeholder="Short description")
        project_type = st.number_input("project_type", min_value=0, value=0, step=1, help="0 = standard/job-based")

    # Optional
    with st.expander("Optional overrides"):
        dbt_cloud_host_url = st.text_input(
            "dbt_cloud_host_url",
            value="",
            placeholder="Leave empty for default (https://cloud.getdbt.com/api)",
        )
        dbt_version = st.text_input("dbt_version", value="latest-fusion")
        staging_branch = st.text_input("staging_branch", value="staging")
        schedule_cron = st.text_input("schedule_cron", value="0 9 * * 1-5", help="Cron for scheduled jobs")
        num_threads = st.number_input("num_threads", min_value=1, value=4, step=1)

    with st.expander("Job trigger toggles (set true to disable)"):
        deactivate_jobs_pr = st.checkbox("deactivate_jobs_pr", value=False)
        deactivate_jobs_merge = st.checkbox("deactivate_jobs_merge", value=False)
        deactivate_jobs_schedule = st.checkbox("deactivate_jobs_schedule", value=False)

    st.divider()

    # Actions
    if not token.strip():
        st.warning("Enter DBT_CLOUD_TOKEN to run Terraform.")
    else:
        workspace_dir = ensure_session_workspace()
        tfvars_content = build_tfvars(
            dbt_cloud_account_id=dbt_cloud_account_id,
            project_id=project_id,
            project_name=project_name or "",
            project_description=project_description or "",
            project_type=project_type,
            connection_id=connection_id,
            credential_id=credential_id,
            dbt_cloud_host_url=dbt_cloud_host_url or None,
            dbt_version=dbt_version or None,
            staging_branch=staging_branch or None,
            schedule_cron=schedule_cron or None,
            num_threads=num_threads,
            deactivate_jobs_pr=deactivate_jobs_pr,
            deactivate_jobs_merge=deactivate_jobs_merge,
            deactivate_jobs_schedule=deactivate_jobs_schedule,
        )
        tfvars_path = Path(workspace_dir) / "terraform.tfvars"
        tfvars_path.write_text(tfvars_content, encoding="utf-8")

        col1, col2, col3, col4 = st.columns(4)
        with col1:
            if st.button("Init"):
                ok, out, err = run_terraform(workspace_dir, token, "init")
                st.code(out + ("\n" + err if err else ""), language="text")
                st.success("Init finished." if ok else "Init had errors.")
        with col2:
            if st.button("Plan"):
                ok, out, err = run_terraform(workspace_dir, token, "plan", "-no-color")
                full = out + ("\n" + err if err else "")
                st.code(full or "(no output)", language="text")
                st.success("Plan finished." if ok else "Plan had errors.")
        with col3:
            if st.button("Apply"):
                ok, out, err = run_terraform(workspace_dir, token, "apply", "-auto-approve", "-no-color")
                full = out + ("\n" + err if err else "")
                st.code(full or "(no output)", language="text")
                st.success("Apply finished." if ok else "Apply had errors.")
        with col4:
            if st.button("Destroy"):
                ok, out, err = run_terraform(workspace_dir, token, "destroy", "-auto-approve", "-no-color")
                full = out + ("\n" + err if err else "")
                st.code(full or "(no output)", language="text")
                st.success("Destroy finished." if ok else "Destroy had errors.")

    with st.expander("Generated terraform.tfvars"):
        if "workspace_dir" in st.session_state:
            tfvars_content = build_tfvars(
                dbt_cloud_account_id=dbt_cloud_account_id,
                project_id=project_id,
                project_name=project_name or "",
                project_description=project_description or "",
                project_type=project_type,
                connection_id=connection_id,
                credential_id=credential_id,
                dbt_cloud_host_url=dbt_cloud_host_url or None,
                dbt_version=dbt_version or None,
                staging_branch=staging_branch or None,
                schedule_cron=schedule_cron or None,
                num_threads=num_threads,
                deactivate_jobs_pr=deactivate_jobs_pr,
                deactivate_jobs_merge=deactivate_jobs_merge,
                deactivate_jobs_schedule=deactivate_jobs_schedule,
            )
            st.code(tfvars_content, language="hcl")
        else:
            st.info("Initialize by running an action above to see generated tfvars.")


if __name__ == "__main__":
    main()
